# Generated by Django 5.1.4 on 2025-01-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_downloader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration_s",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="upload_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="uploader",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="views",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
