# Generated by Django 5.1.4 on 2025-01-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "youtube_downloader",
            "0002_video_duration_s_video_upload_date_video_uploader_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="upload_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
