# Generated by Django 5.1.4 on 2025-01-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_downloader", "0003_alter_video_upload_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(),
        ),
    ]
