# Generated by Django 5.1.4 on 2025-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_downloader", "0004_alter_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Baixado", "Baixado"),
                    ("Excluído", "Excluído"),
                ],
                default="Pendente",
                max_length=50,
            ),
        ),
    ]
