# Generated by Django 5.1.4 on 2025-01-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_downloader", "0005_alter_video_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["-updated_at"]},
        ),
    ]
