# Generated by Django 5.1.4 on 2025-01-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_downloader", "0007_video_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
