version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - django_data:/app/db 
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core worker --loglevel=info
    depends_on:
      - rabbitmq
    volumes:
      - .:/app 
      - django_data:/app/db 
    environment:           
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DJANGO_SETTINGS_MODULE=core.settings

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - rabbitmq
    volumes:
      - .:/app 
      - django_data:/app/db 
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DJANGO_SETTINGS_MODULE=core.settings

volumes:
  django_data:
    driver: local
